manager/urls.py
from django.urls import path

from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index_page'),
    path('login/', views.LoginPage.as_view(), name='login_page'),
    path('logout/', views.logout_action, name='logout'),
    path('dashboard/', views.DashboardPage.as_view(), name='dashboard_page'),
    path('devices/<int:pk>/', views.DevicePage.as_view(), name='device_page'),
]

manager/models.py
import json

from django.db import models
from django.utils.translation import gettext_lazy as _


class Device(models.Model):

    name = models.CharField(max_length=100, verbose_name=_('Device name'))
    ipv4 = models.GenericIPAddressField(protocol='IPv4', verbose_name=_('IPv4 address'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Created datetime'))

    class Meta:
        verbose_name = 'IoT Device'
        verbose_name_plural = 'IoT Devices'

    def __str__(self):
        return f'{self.ipv4} - {self.name}'

    def analyze_history(self):
        result = {
            'name': self.name,
            'address': self.ipv4,
            'created_date': self.created_date,
        }

        device_history = DeviceAnalyzeHistory.objects.filter(device_id=self.pk)
        stats = {
            'prediction_score_sum': 0,
            'prediction_score_count': 0,
            'payload_count': 0,
            'packet_length': 0,
            'analysis_count': 0,
        }
        for history in device_history:  # type: DeviceAnalyzeHistory
            history.analyze_history(stats)

        if stats['prediction_score_count'] > 0:
            device_stat = {
                'prediction_score_avg': round(
                    stats['prediction_score_sum'] / stats['prediction_score_count'], 3
                ),
                'payload_count': stats['payload_count'],
            }
        else:
            device_stat = {
                'prediction_score_avg': 'Undef.',
                'payload_count': 0
            }

        device_stat['packet_length'] = stats['packet_length']
        device_stat['analysis_count'] = stats['analysis_count']
        result.update(device_stat)
        return result


class DeviceAnalyzeHistory(models.Model):

    device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name=_('Device'))
    result = models.TextField(verbose_name=_('Analysis result'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create datetime'))

    class Meta:
        verbose_name = 'IoT Network Analysis'
        verbose_name_plural = 'IoT Network Analysis'

    def __str__(self):
        return f'Analysis: {self.device}'

    def analyze_history(self, stats: dict):
        result = self.result
        stats['analysis_count'] += 1

        try:
            result_json = json.loads(result)
            stats['prediction_score_sum'] += result_json.get('prediction_score', 0)
            stats['prediction_score_count'] += 1
            stats['payload_count'] = sum(
                1 for i in result_json.get('analysis', list()) if i.get('has_file_payload')
            )
            stats['packet_length'] += sum(
                i.get('packet_length', 0) for i in result_json.get('analysis', list())
            ) // 10 ** 6
        except:  # noqa
            pass

        return stats

manager/forms.py
from django import forms

from . import models


class DeviceForm(forms.ModelForm):

    class Meta:
        model = models.Device
        fields = '__all__'


class AnalysisForm(forms.Form):

    pcap_file = forms.FileField()

    class Meta:
        fields = '__all__'

manager/views.py
import json
import traceback
from copy import deepcopy

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from core import DatasetType
from core.analyzer.network import NetworkAnalyzer
from core.ml.predictor import Predictor
from manager.forms import DeviceForm, AnalysisForm
from manager.models import Device, DeviceAnalyzeHistory


class IndexPage(TemplateView):
    template_name = 'manager/index_page.html'


class LoginPage(TemplateView):
    template_name = 'manager/login_page.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not (username and password):
            messages.error(request, 'Username and password are required!')
            return redirect(reverse('manager:login_page'))

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('manager:dashboard_page'))

        messages.error(request, 'User authentication failed. Try again!')
        return redirect(reverse('manager:login_page'))


def logout_action(request):
    logout(request)
    return redirect(reverse('manager:index_page'))


class DashboardPage(TemplateView):
    template_name = 'manager/dashboard_page.html'
    form = DeviceForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        devices = {}
        for device in Device.objects.all():
            device_stat = device.analyze_history()
            devices[device.pk] = device_stat

        ctx['devices'] = devices

        return ctx

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)

        redirect_url = 'manager:dashboard_page'
        redirect_kwargs = None
        if form.is_valid():
            device = form.save()
            redirect_url = 'manager:device_page'
            redirect_kwargs = dict(pk=device.pk)
        else:
            messages.error(request, 'Invalid form. Check for errors')

        return redirect(reverse(redirect_url, kwargs=redirect_kwargs))


class DevicePage(TemplateView):
    template_name = 'manager/device_page.html'
    form = AnalysisForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        history = DeviceAnalyzeHistory.objects.filter(
            device_id=kwargs['pk']
        ).order_by('-pk').select_related('device')

        history_data = {}
        overall_stats = {
            'prediction_score_sum': 0,
            'prediction_score_count': 0,
            'payload_count': 0,
            'packet_length': 0,
            'analysis_count': 0,
            'prediction_score_avg': 0,
        }

        for history_obj in history:  # type: DeviceAnalyzeHistory
            history_obj_stat = deepcopy(overall_stats)
            history_obj_stat = history_obj.analyze_history(history_obj_stat)
            history_obj_stat.update(dict(
                created_date=history_obj.created_date,
                result=history_obj.result,
            ))

            prediction_score_avg = 'Undef.'
            if history_obj_stat.get('prediction_score_count') > 0:
                prediction_score_avg = round(
                    history_obj_stat.get('prediction_score_sum', 0) /
                    history_obj_stat.get('prediction_score_count'), 2
                )
            history_obj_stat['prediction_score_avg'] = prediction_score_avg

            history_data[history_obj.pk] = history_obj_stat

        for stat in history_data.values():
            for stat_key, stat_val in stat.items():
                if isinstance(stat_val, (int, float)):
                    overall_stats[stat_key] += stat_val

        if history:
            overall_stats['created_date'] = history.first().device.created_date

        ctx['history'] = history_data
        ctx['overall_stats'] = overall_stats
        return ctx

    def post(self, request, *args, **kwargs):

        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            try:
                analyzer = NetworkAnalyzer()
                analysis = analyzer.analyze(form.cleaned_data['pcap_file'])

                predictor = Predictor(DatasetType.NETWORK, output_feature='is_malicious')
                prediction = list(predictor.predict(analysis))

                score = sum(prediction) / len(prediction)

                result = {
                    'analysis': analysis,
                    'prediction_score': score,
                }

                DeviceAnalyzeHistory.objects.create(
                    device_id=kwargs['pk'],
                    result=json.dumps(result)
                )

                messages.info(request, 'Analysis is ready to check')
            except:  # noqa
                traceback.print_exc()
                messages.error(request, 'Something went wrong in processing. Try again later!')
        else:
            messages.error(request, 'Form is invalid')

        return redirect(reverse('manager:device_page', kwargs=kwargs))

manager/templates/manager/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">

    <!--Meta Keywords and Description-->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'manager/images/favicon.ico' %}" title="Favicon"/>

    <!-- Main CSS Files -->
    <link rel="stylesheet" href="{% static 'manager/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'manager/css/styleguide.css' %}">
    <link rel="stylesheet" href="{% static 'manager/css/style1.css' %}">


    <!-- Namari Color CSS -->
    <link rel="stylesheet" href="{% static 'manager/css/namari-color.css' %}">

    <!--Icon Fonts - Font Awesome Icons-->
    <link rel="stylesheet" href="{% static 'manager/css/font-awesome.min.css' %}">

    <!-- Animate CSS-->
    <link href="{% static 'manager/css/animate.css' %}" rel="stylesheet" type="text/css">

    <!--Google Webfonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

manager/templates/manager/dashboard_page.html
{% extends 'manager/base.html' %}
{% load static %}

{% block title %} Dashboard {% endblock %}

{% block body %}

    {% include 'manager/loader.html' %}

    <div class="page-border" data-wow-duration="0.7s" data-wow-delay="0.2s">
        <div class="top-border wow fadeInDown animated" style="visibility: visible; animation-name: fadeInDown;"></div>
        <div class="right-border wow fadeInRight animated" style="visibility: visible; animation-name: fadeInRight;"></div>
        <div class="bottom-border wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;"></div>
        <div class="left-border wow fadeInLeft animated" style="visibility: visible; animation-name: fadeInLeft;"></div>
    </div>

    <div id="wrapper">

        <header id="banner2" class="scrollto clearfix" data-enllax-ratio=".5">
            {% include 'manager/header.html' %}
        </header>

        <!--Main Content Area-->
        <main id="content">

            <!--Devices Tables-->
            <section id="pricing" class="secondary-color text-center scrollto clearfix ">
                <div class="row clearfix">

                    {% if devices %}
                        <div class="section-heading">
                            <h3>YOUR DEVICES</h3>
                            <h2 class="section-title">Manager Your IoT Devices</h2>
                        </div>
                        {% for device_id, device in devices.items %}
                            <!--Device Block-->
                            <div class="pricing-block col-3 wow fadeInUp" data-wow-delay="0.4s">
                                <div class="pricing-block-content">
                                    <h3>{{ device.name }}</h3>
                                    <div class="pricing">
                                        <div class="price">{{ device.prediction_score_avg }}</div>
                                        <p>Malicious Activity - Prediction Score</p>
                                    </div>
                                    <ul>
                                        <li>{{ device.analysis_count }} analysis provided</li>
                                        <li>{{ device.payload_count }} file payloads</li>
                                        <li>{{ device.packet_length }} MB of data volume</li>
                                        <li>Created at {{ device.created_date }}</li>
                                    </ul>
                                    <a href="{% url 'manager:device_page' device_id %}" class="button">Details</a>
                                </div>
                            </div>
                            <!--End Device Block-->
                        {% endfor %}
                    {% else %}
                        <div class="section-heading">
                            <h3>YOUR DEVICES</h3>
                            <h2 class="section-title">Add your IoT devices to manage</h2>
                        </div>
                    {% endif %}

                </div>
            </section>
            <!--End of Devices Tables-->

            <!--New Device-->
            <section id="newDevice" class="secondary-color text-center scrollto clearfix ">
                <div class="row clearfix">
                    <div class="section-heading">
                        <h3>NEW DEVICE</h3>
                        <h2 class="section-title">Create New Device</h2>
                    </div>
                    <div class="pricing-block text-center wow fadeInUp mx-auto" data-wow-delay="0.4s">
                        <form class="form" method="POST">
                            {% csrf_token %}

                            <div class="input-group text-center">
                                <label for="name">Name of device:</label>
                            </div>
                            <div class="input-group text-center">
                                <input type="text" class="form-control" style="width: 300px;" name="name" id="name" required>
                            </div>
                            <div class="input-group text-center">
                                <label for="ipv4">IPv4 address:</label>
                            </div>
                            <div class="input-group text-center">
                                <input type="text" class="form-control" style="width: 300px;" name="ipv4" id="ipv4" required>
                            </div>
                            <div class="input-group text-center">
                                <input type="submit" value="Create device" class="button">
                            </div>
                        </form>
                    </div>
                </div>
            </section>

        </main>
        <!--End Main Content Area-->

    </div>

    <!-- Include JavaScript resources -->
    <script src="{% static 'manager/js/jquery.1.8.3.min.js' %}"></script>
    <script src="{% static 'manager/js/wow.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.gallery.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.enllax.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.stickyNavbar.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'manager/js/images-loaded.min.js' %}"></script>
    <script src="{% static 'manager/js/lightbox.min.js' %}"></script>
    <script src="{% static 'manager/js/site.js' %}"></script>

{% endblock %}

manager/templates/manager/device_page.html
{% extends 'manager/base.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block body %}

    {% include 'manager/loader.html' %}

    <div class="page-border" data-wow-duration="0.7s" data-wow-delay="0.2s">
        <div class="top-border wow fadeInDown animated" style="visibility: visible; animation-name: fadeInDown;"></div>
        <div class="right-border wow fadeInRight animated" style="visibility: visible; animation-name: fadeInRight;"></div>
        <div class="bottom-border wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;"></div>
        <div class="left-border wow fadeInLeft animated" style="visibility: visible; animation-name: fadeInLeft;"></div>
    </div>

    <div id="wrapper">
        <header id="banner3" class="scrollto clearfix" data-enllax-ratio=".5">
            {% include 'manager/header.html' %}

            <!--Banner Content-->
            <div id="banner-content" class="row clearfix" style="min-height: 600px;">

                <div class="col-38">

                    <div class="section-heading">
                        <h1>IoT Devices Stats</h1>
                        <p>
                            <ul>
                                <li>{{ overall_stats.analysis_count }} analysis provided</li>
                                <li>{{ overall_stats.payload_count }} file payloads</li>
                                <li>{{ overall_stats.packet_length }} MB of data volume</li>
                                {% if overall_stats.created_date %}
                                    <li>{{ overall_stats.created_date }} is first seen</li>
                                {% endif %}
                            </ul>
                        </p>
                    </div>

                </div>

            </div><!--End of Row-->

        </header>

        <!--Main Content Area-->
        <main id="content">
            <!--History Analysis Tables-->
            <section id="pricing" class="secondary-color text-center scrollto clearfix ">
                <div class="row clearfix">

                    {% if history %}
                        <div class="section-heading">
                            <h3>DEVICE HISTORY</h3>
                            <h2 class="section-title">Process history</h2>
                        </div>
                        {% for history_id, history_obj in history.items %}
                            <!--History Analysis Block-->
                            <div class="pricing-block col-3 wow fadeInUp" data-wow-delay="0.4s">
                                <div class="pricing-block-content">
                                    <h3>Analysis: {{ history_obj.created_date }}</h3>
                                    <div class="pricing">
                                        <div class="price">{{ history_obj.prediction_score_avg }}</div>
                                        <p>Malicious Activity - Prediction Score</p>
                                    </div>
                                    <ul>
                                        <li>{{ history_obj.analysis_count }} analysis provided</li>
                                        <li>{{ history_obj.payload_count }} file payloads</li>
                                        <li>{{ history_obj.packet_length }} MB of data volume</li>
                                        <li>
                                            <a id="download_{{ history_id }}"
                                               download="analysis_{{ history_id }}.json"
                                               type="text/json"> Download analysis JSON
                                            </a>
                                            <p id="download_{{ history_id }}_data" hidden>{{ history_obj.result }}</p>
                                            <script>
                                                let json = document.getElementById('download_{{ history_id }}_data').innerText;
                                                let data = new Blob([json]);
                                                let link_to_download = document.getElementById('download_{{ history_id }}');
                                                link_to_download.href = URL.createObjectURL(data);
                                            </script>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!--End History Analysis Block-->
                        {% endfor %}
                    {% else %}
                        <div class="section-heading">
                            <h3>DEVICE HISTORY</h3>
                            <h2 class="section-title">No history is processed yet</h2>
                        </div>
                    {% endif %}

                </div>
            </section>
            <!--End of History Analysis Tables-->

            <!--New Device-->
            <section id="newDevice" class="secondary-color text-center scrollto clearfix ">
                <div class="row clearfix">
                    <div class="section-heading">
                        <h3>NEW ANALYSIS</h3>
                        <h2 class="section-title">Process PCAP analysis</h2>
                    </div>
                    <div class="pricing-block text-center wow fadeInUp mx-auto" data-wow-delay="0.4s">
                        <form class="form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="input-group text-center">
                                <label for="pcap_file">PCAP File for analysis:</label>
                            </div>
                            <div class="input-group">
                                <input type="file" class="form-control" name="pcap_file" id="pcap_file" required>
                            </div>
                            <div class="input-group text-center">
                                <input type="submit" value="Process Analysis" class="button">
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </main>

    </div>

    <!-- Include JavaScript resources -->
    <script src="{% static 'manager/js/jquery.1.8.3.min.js' %}"></script>
    <script src="{% static 'manager/js/wow.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.gallery.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.enllax.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.stickyNavbar.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'manager/js/images-loaded.min.js' %}"></script>
    <script src="{% static 'manager/js/lightbox.min.js' %}"></script>
    <script src="{% static 'manager/js/site.js' %}"></script>

{% endblock %}

manager/templates/manager/header.html
{% load static %}

{% block header %}
<div id="header" class="nav-collapse">
    <div class="row clearfix">
        <div class="col-1">

            <!--Main Navigation-->
            <nav id="nav-main">
                <ul>
                    <li>
                        <a href="{% url 'manager:index_page' %}">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'manager:dashboard_page' %}">Dashboard</a>
                        </li>
                    {% endif %}
                    <li>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'manager:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'manager:login_page' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
            <!--End of Main Navigation-->

            <div id="nav-trigger"><span></span></div>
            <nav id="nav-mobile"></nav>

        </div>
    </div>
</div><!--End of Header-->
{% endblock %}

manager/templates/manager/loader.html
<!-- Preloader -->
<div id="preloader">
    <div id="status" class="la-ball-triangle-path">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!--End of Preloader-->

manager/templates/manager/login_page.html
{% extends 'manager/base.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block body %}

    {% include 'manager/loader.html' %}

    <div class="page-border" data-wow-duration="0.7s" data-wow-delay="0.2s">
        <div class="top-border wow fadeInDown animated" style="visibility: visible; animation-name: fadeInDown;"></div>
        <div class="right-border wow fadeInRight animated" style="visibility: visible; animation-name: fadeInRight;"></div>
        <div class="bottom-border wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;"></div>
        <div class="left-border wow fadeInLeft animated" style="visibility: visible; animation-name: fadeInLeft;"></div>
    </div>

    <div id="wrapper">

        <header id="banner2" class="scrollto clearfix" data-enllax-ratio=".5">
            {% include 'manager/header.html' %}

            <!--Banner Content-->
            <div id="banner-content" class="row clearfix">

                <div class="col-38">

                    <div class="section-heading">
                        <h1 class="text-center m-auto">Get Your Power</h1>
                        <form class="form" method="POST">
                            {% csrf_token %}
                            <div class="input-group text-center">
                                <input type="text" class="form-control" name="username" id="username" required>
                            </div>
                            <div class="input-group text-center">
                                <input type="password" class="form-control" name="password" id="password" required>
                            </div>
                            <div class="input-group text-center">
                                <input type="submit" value="Login" class="button">
                            </div>
                        </form>

                    </div>

                </div>

            </div><!--End of Row-->

        </header>

    </div>

    <!-- Include JavaScript resources -->
    <script src="{% static 'manager/js/jquery.1.8.3.min.js' %}"></script>
    <script src="{% static 'manager/js/wow.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.min.js' %}"></script>
    <script src="{% static 'manager/js/featherlight.gallery.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.enllax.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.stickyNavbar.min.js' %}"></script>
    <script src="{% static 'manager/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'manager/js/images-loaded.min.js' %}"></script>
    <script src="{% static 'manager/js/lightbox.min.js' %}"></script>
    <script src="{% static 'manager/js/site.js' %}"></script>

{% endblock %}